import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { dbConfig } from "./utils/dbConfig";
import Header from "./Header";
import MainProvider from "./MainProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConfig();
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainProvider>
          <div>
            <Header />
            <div>{children}</div>
          </div>
        </MainProvider>
      </body>
    </html>
  );
}
